.TH "__slow5idx_t" 3 "Wed Oct 14 2020" "slow5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__slow5idx_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSLOW5_FILE\fP * \fBslow5\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "int \fBm\fP"
.br
.ti -1c
.RI "char ** \fBname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for slow5 from the source code\&.
