.TH "command" 3 "Wed Oct 14 2020" "slow5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
command
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int(* \fBmain\fP )(int, char **, struct \fBprogram_meta\fP *)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for slow5 from the source code\&.
