.TH "fast5_t" 3 "Wed Oct 14 2020" "slow5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fast5_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t * \fBrawptr\fP"
.br
.ti -1c
.RI "uint64_t \fBnsample\fP"
.br
.ti -1c
.RI "float \fBdigitisation\fP"
.br
.ti -1c
.RI "float \fBoffset\fP"
.br
.ti -1c
.RI "float \fBrange\fP"
.br
.ti -1c
.RI "float \fBsample_rate\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "float \fBshift\fP"
.br
.ti -1c
.RI "float \fBdrift\fP"
.br
.ti -1c
.RI "float \fBvar\fP"
.br
.ti -1c
.RI "float \fBscale_sd\fP"
.br
.ti -1c
.RI "float \fBvar_sd\fP"
.br
.ti -1c
.RI "float \fBlog_var\fP"
.br
.ti -1c
.RI "float \fBscaled_var\fP"
.br
.ti -1c
.RI "float \fBlog_scaled_var\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for slow5 from the source code\&.
