.TH "format_map" 3 "Wed Oct 14 2020" "slow5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
format_map
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "enum \fBslow5idx_format_options\fP \fBformat\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for slow5 from the source code\&.
