.TH "hFILE" 3 "Wed Oct 14 2020" "slow5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hFILE \- Low-level input/output stream handle\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hfile\&.h>\fP
.SH "Detailed Description"
.PP 
Low-level input/output stream handle\&. 

The fields of this structure are declared here solely for the benefit of the hFILE-related inline functions\&. They may change in future releases\&. User code should not use them directly; you should imagine that \fBhFILE\fP is an opaque incomplete type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for slow5 from the source code\&.
