.TH "ks_tokaux_t" 3 "Wed Oct 14 2020" "slow5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ks_tokaux_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBtab\fP [4]"
.br
.ti -1c
.RI "int \fBsep\fP"
.br
.ti -1c
.RI "int \fBfinished\fP"
.br
.ti -1c
.RI "const char * \fBp\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for slow5 from the source code\&.
